srcRedis:
  passwd: sdfsdfsdf
  url:
    - localhost:17001
    - localhost:17002
    - localhost:17003
    - localhost:17004
    - localhost:17005
    - localhost:17006

destRedis:
  password: sadfsadfs
  url:
    - localhost:31046
    - localhost:31047